all:
	make -C bucketsort
	make -C countsort
	make -C heapsort
	make -C quicksort

clean:
	make clean -C bucketsort
	make clean -C countsort
	make clean -C heapsort
	make clean -C quicksort
